### PR TITLE
TrackPoint reading: filter on contentResolver layer

### PR DESCRIPTION
**Pull request by dennisguse**
Should improve performance while recording.

Follow-up to https://mastodon.social/@swh/104994470745313645

NOT TESTED, because I am not yet sure how ;)

### CODE REVIEW

**Comment by pstorch** [comment]
Thanks, why didn't I see that? I'll test later today.

**Comment by dennisguse** [comment]
Just a disclaimer: there is still another problem (just my gut feeling).
Not iterating over all trackpoints again will save a lot, but we might still might have a memory leak (temporary or permanent) somewhere else.

**Comment by dennisguse** [comment]
Stream processing?
Another improvement would be to use the cursor directly to create the objects needed by mapsforge (aka latlong) and pass it directly to mapsforge.
At the moment, the data is read from the cursor completely as List<List<TrackPoint>> and afterwards processed before passing it to mapsforge.

**Comment by pstorch** [comment]
Stream processing is not possible anymore since we introduced the TrackSmoothing. Or we need to implement 2 different ways (which I would like to avoid).
At the moment I have some doubts if that cursor processing is the problem. The issue only happens with live tracks and in this case we don't get many new Track points on each update, usually 1 or 2. And the affected user could reproduce the issue in very short time, so I guess we don't have a long track with many track points. But optimizing unnecessary track point processing would benefit nevertheless.
I also want to build a version of the released tag, but with old mapsforge lib, just to make if this makes a difference.

**Comment by pstorch** [comment]
There was a problem with the beginning of the while clause, but the selection criteria is working as well. And I don't think we need to make the lastTrackPointId nullable, 0 is good.

I've also refactored the registration of the ContentObserver and added an unregister to not cause unecessary reads from obsolete URIs. That should also cleanup a little bit.

**Pull request merged**
