### PR TITLE
fix #70 add offline only build flavor

### LINKED ISSUE #70: Introduce offline only variant of OSMDashboard
From: https://github.com/OpenTracksApp/OpenTracks/issues/412#issuecomment-688513847
For users with high requirements on privacy a version of OSMDashboard without internet access would be appreciated.

Build a variant of OSMDashboard without internet permission. This can probably be achieved by a build flavor.

### PR DESCRIPTION
**Pull request by pstorch**
Added a build flavor "offline" without internet permission.

TBC: the handling of the fastlane metadata

### CODE REVIEW

**Comment by pstorch** [comment]
@dennisguse @rgmf can someone do a quick test if this still works for you and doesn't break anything?

**Comment by rgmf** [comment]
@pstorch if I select flavor offline to build then I shouldn't see online maps, right?

**Comment by pstorch** [comment]
@rgmf correct. And the InApp download of Offline Maps is also missing. If you build it with this flavor you get a new App icon in green.

**Comment by pstorch** [comment]
I'll try to build it on F-Droid

**Pull request merged**
