### PR TITLE
Android 12 needs to declare the new HIGH_SAMPLING_RATE_SENSORS permission in Manifest.

### LINKED ISSUE #130: To use the sampling rate of 0 microseconds, app needs to declare the normal permission HIGH_SAMPLING_RATE_SENSORS.
I can't use app in Android 12. Here logs:

```log
2021-12-03 23:58:55.723 28290-28290/de.storchp.opentracks.osmplugin.debug E/AndroidRuntime: FATAL EXCEPTION: main
    Process: de.storchp.opentracks.osmplugin.debug, PID: 28290
    java.lang.RuntimeException: Unable to resume activity {de.storchp.opentracks.osmplugin.debug/de.storchp.opentracks.osmplugin.MapsActivity}: java.lang.SecurityException: To use the sampling rate of 0 microseconds, app needs to declare the normal permission HIGH_SAMPLING_RATE_SENSORS.
        at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4757)
        at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:4790)
        at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:54)
        at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2210)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loopOnce(Looper.java:201)
        at android.os.Looper.loop(Looper.java:288)
        at android.app.ActivityThread.main(ActivityThread.java:7838)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
     Caused by: java.lang.SecurityException: To use the sampling rate of 0 microseconds, app needs to declare the normal permission HIGH_SAMPLING_RATE_SENSORS.
        at android.hardware.SystemSensorManager$BaseEventQueue.enableSensor(SystemSensorManager.java:792)
        at android.hardware.SystemSensorManager$BaseEventQueue.addSensor(SystemSensorManager.java:712)
        at android.hardware.SystemSensorManager.registerListenerImpl(SystemSensorManager.java:209)
        at android.hardware.SensorManager.registerListener(SensorManager.java:832)
        at android.hardware.SensorManager.registerListener(SensorManager.java:739)
        at de.storchp.opentracks.osmplugin.compass.AbstractLowPassSensor.startImpl(AbstractLowPassSensor.java:58)
        at de.storchp.opentracks.osmplugin.compass.AbstractSensor.start(AbstractSensor.java:19)
        at de.storchp.opentracks.osmplugin.compass.Compass.startImpl(Compass.java:95)
        at de.storchp.opentracks.osmplugin.compass.AbstractSensor.start(AbstractSensor.java:19)
        at de.storchp.opentracks.osmplugin.MapsActivity.onResume(MapsActivity.java:762)
        at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1476)
        at android.app.Activity.performResume(Activity.java:8191)
        at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4747)
        at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:4790) 
        at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:54) 
        at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45) 
        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2210) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loopOnce(Looper.java:201) 
        at android.os.Looper.loop(Looper.java:288) 
        at android.app.ActivityThread.main(ActivityThread.java:7838) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003) 
```

### PR DESCRIPTION
**Pull request by rgmf**
This PR fixes #130 issue in Android 12.
More info: https://proandroiddev.com/review-of-android-12-for-developers-ea3ce9247e0

### CODE REVIEW

**Comment by dennisguse** [comment]
Is this really required? Wouldn't it be better to reduce the sampling rate?
I mean processing it requires a lot of processing power (not good on older devices).
Could we not also live with `SENSOR_DELAY_UI`?

@rgmf  congrats to your Android12 upgrade :sunglasses:

**Comment by rgmf** [comment]
> Is this really required? Wouldn't it be better to reduce the sampling rate? I mean processing it requires a lot of processing power (not good on older devices). Could we not also live with `SENSOR_DELAY_UI`?
> 

If that's possible then it would be a better solution.

> @rgmf congrats to your Android12 upgrade sunglasses

The new UI it's really, really ugly... I don't like at all :vomiting_face:

**Comment by pstorch** [comment]
I think even SENSOR_DELAY_GAME should be enough.

**Comment by rgmf** [comment]
@pstorch Yes, it's enough.

**Comment by pstorch** [comment]
I'll change the sensor delay

**Pull request closed without merging**
